# Generated by Django 4.2.1 on 2023-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seats',
            field=models.CharField(max_length=1),
        ),
    ]
