# Generated by Django 4.2.1 on 2023-11-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_timechoice_alter_reservation_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeChoice',
        ),
    ]
