# Generated by Django 4.2.1 on 2023-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_delete_timechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='menu',
            field=models.TextField(blank=True),
        ),
    ]
