# Generated by Django 4.2.1 on 2023-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='menu',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
