# Generated by Django 4.2.7 on 2023-11-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='menu',
            field=models.TextField(blank=True),
        ),
    ]
