# Generated by Django 4.2.7 on 2023-11-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reminder_sent',
        ),
    ]
