# Generated by Django 4.2.7 on 2023-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/1.png', null=True, upload_to='profile_photos/'),
        ),
    ]
