# Generated by Django 4.2.7 on 2023-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/profile-picture.png', upload_to='profile_photos/'),
        ),
    ]
