# Generated by Django 4.2.7 on 2023-11-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_remove_reservation_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
