# Generated by Django 4.2.7 on 2023-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_remove_food_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu',
            field=models.TextField(blank=True),
        ),
    ]
