# Generated by Django 4.2.7 on 2023-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_delete_food_reservation_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='food_quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
