# Generated by Django 4.2.7 on 2023-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_alter_reservation_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='menu',
            field=models.TextField(blank=True),
        ),
    ]
